apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.configMap.name }}
data:
  nginx.conf: |-
    user nginx;
    worker_processes  3;
    error_log  /var/log/nginx/error.log;
    events {
      worker_connections  10240;
    }
    http {
      server {
          listen       8080;
          server_name  _;
          location / {
            root   /usr/share/nginx/html;
            index  index.html index.htm;
          }
          location /api/v1/movies {
            proxy_pass http://movie-api-svc.{{ .Release.Namespace }}.svc.cluster.local:30001/api/v1/movies;
          }
          location /api/v1/casts {
            proxy_pass http://cast-api-svc.{{ .Release.Namespace }}.svc.cluster.local:30002/api/v1/casts;
          }
      }
    }
