apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-svc
  labels:
    {{- include "nginx.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      protocol: TCP
      name: http
      targetPort: {{ $.Values.service.targetPort }}
      nodePort: {{ $.Values.service.nodePort }}
  selector:
    {{- include "nginx.selectorLabels" . | nindent 4 }}
