apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ $.Values.db.persistentVolumeClaim.name }}
  labels:
    app: {{ $.Values.db.name }}
spec:
  resources:
    requests:
      storage: {{ $.Values.storage.size }}
  accessModes:
    - ReadWriteOnce
  storageClassName: {{ $.Values.storage.storageClassName }}
