apiVersion: v1
data:
  POSTGRES_DB: Y2FzdF9kYl9kZXY=
  POSTGRES_PASSWORD: Y2FzdF9kYl9wYXNzd29yZA==
  POSTGRES_USER: Y2FzdF9kYl91c2VybmFtZQ==
kind: Secret
metadata:
  creationTimestamp: null
  name: {{ $.Values.db.secret.name }}
