apiVersion: v1
data:
  DATABASE_URI: postgresql://movie_db_username:movie_db_password@db-movie-svc:5432/movie_db_dev
  CAST_SERVICE_HOST_URL: http://cast-api-svc.{{ .Release.Namespace }}.svc.cluster.local:30002/api/v1/casts/
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: {{ $.Values.db.configMap.name }}
