apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: {{ $.Values.db.service.name }}
  name: {{ $.Values.db.service.name }}
spec:
  ports:
  - name: {{ $.Values.db.service.name }}
    port: {{ $.Values.db.service.port }}
    protocol: TCP
    targetPort: {{ $.Values.db.service.port }}
  selector:
    app: {{ $.Values.db.name }}
  type: {{ $.Values.db.service.type }}
status:
  loadBalancer: {}
