apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: {{ $.Values.service.name }}
  name: {{ $.Values.service.name }}
spec:
  ports:
  - name: 80-5001
    port: {{ $.Values.service.port }}
    protocol: {{ $.Values.service.protocol }}
    targetPort: {{ $.Values.service.targetPort }}
    nodePort: {{ $.Values.service.nodePort }}
  selector:
    app: {{ $.Values.name }}
  type: {{ $.Values.service.type }}
status:
  loadBalancer: {}
